[project]
name = "proto-mangle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "proto-schema-parser>=1.5.0",
    "ruff>=0.9.7",
]
